# This is a basic workflow to help you get started with Actions

name: Wheels

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64]
        include:
          - os: ubuntu-latest
            arch: aarch64

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
      
      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          python setup.py install

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.11.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: ${{matrix.arch}}
          CIBW_SKIP: "cp27-* cp35-* cp36-* pp*"  # skip Python 2.7 wheels
          CIBW_BEFORE_BUILD: "rm -rf build/"

      - name: Upload wheels
        run: |
          python -m pip install twine
          python -m twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} ./wheelhouse/*.whl
          
